name: Build PS3

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/ps3dev/ps3dev:latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: make

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ps3-build
          path: . 
